#!/usr/bin/env python3
"""Build a hybrid pitch video:
- PPT slides for intro/outro
- Real app demo screen recording for the demo section
- Uses edge-tts audio generated by build_pitch_video.py
"""

import asyncio
import os
import subprocess
import sys
from pathlib import Path

from playwright.async_api import async_playwright

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from app.core.video_builder import _get_duration

PITCH_DIR = "/Volumes/extdisk/project/sui/proofPay/pitch"
BACKEND_OUTPUT = os.path.join(PITCH_DIR, "backend-output")
AUDIO_DIR = os.path.join(BACKEND_OUTPUT, "audio")
PPT_FRAMES_DIR = BACKEND_OUTPUT
DEMO_OUTPUT_DIR = os.path.join(PITCH_DIR, "hybrid-temp")
FINAL_OUTPUT = os.path.join(PITCH_DIR, "proofpay-pitch-hybrid.mp4")

# Which slides use app demo footage instead of PPT slides
DEMO_SLIDES = {4, 5, 6}


def run_ffmpeg(cmd):
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def build_image_clip(image_path, audio_path, output_path):
    duration = _get_duration(audio_path)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    run_ffmpeg([
        "ffmpeg", "-y", "-loop", "1", "-i", image_path,
        "-i", audio_path,
        "-c:v", "libx264", "-tune", "stillimage",
        "-c:a", "aac", "-b:a", "192k",
        "-pix_fmt", "yuv420p", "-shortest", "-t", str(duration),
        "-vf", "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2",
        output_path,
    ])


def extract_video_clip(video_path, audio_path, output_path, start_sec, end_sec):
    """Extract a sub-clip from a longer video and match audio duration."""
    target_duration = _get_duration(audio_path)
    source_duration = end_sec - start_sec
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    # If durations differ, adjust playback speed to match target
    if abs(source_duration - target_duration) < 0.05:
        speed_filter = ""
    else:
        speed = source_duration / target_duration
        speed_filter = f",setpts=PTS/{speed}"

    run_ffmpeg([
        "ffmpeg", "-y",
        "-ss", str(start_sec), "-to", str(end_sec), "-i", video_path,
        "-i", audio_path,
        "-c:v", "libx264", "-c:a", "aac", "-b:a", "192k",
        "-pix_fmt", "yuv420p", "-shortest", "-t", str(target_duration),
        "-vf", f"scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2{speed_filter}",
        "-af", f"atempo=1.0",
        output_path,
    ])


async def record_demo_video(output_path, segment_durations):
    """Record a demo video split into three segments with target durations."""
    # Clean up previous recordings so we always use the latest footage
    for f in os.listdir(DEMO_OUTPUT_DIR):
        if f.endswith(".webm"):
            os.remove(os.path.join(DEMO_OUTPUT_DIR, f))

    total_duration = sum(segment_durations)
    # Heuristic: recorded duration tends to be ~1.27x of sum of wait times.
    # Adjust step_time down to compensate.
    num_steps = 9  # connect wallet + 7 demo steps + verify page
    step_time = max(4.0, (total_duration / num_steps) / 1.25)

    print(f"Recording demo video: target={total_duration:.2f}s, step_time={step_time:.2f}s")

    # Expect dev server already running on localhost:3002
    await asyncio.sleep(1)

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            record_video_dir=DEMO_OUTPUT_DIR,
            record_video_size={"width": 1280, "height": 720},
        )
        page = await context.new_page()
        await page.goto("http://localhost:3002/demo")
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Connect Demo Wallet")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Create Demo Settlement")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Submit Failed Delivery")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Run Failed Review")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Submit Corrected Delivery")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Run Passing Review")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Approve & Release")')
        await asyncio.sleep(step_time)

        await page.click('button:has-text("Verify Passport")')
        await asyncio.sleep(step_time)

        await page.goto("http://localhost:3002/verify")
        await page.click('button:has-text("View ResearchBot-01 Passport")')
        await asyncio.sleep(step_time)

        await context.close()
        await browser.close()

    # Find the most recently recorded webm
    files = [
        f for f in os.listdir(DEMO_OUTPUT_DIR) if f.endswith(".webm")
    ]
    if not files:
        raise RuntimeError("No demo video recorded")
    files.sort(key=lambda f: os.path.getmtime(os.path.join(DEMO_OUTPUT_DIR, f)))
    webm = os.path.join(DEMO_OUTPUT_DIR, files[-1])

    # Convert to mp4
    run_ffmpeg([
        "ffmpeg", "-y", "-i", webm,
        "-c:v", "libx264", "-preset", "fast", "-crf", "23",
        "-pix_fmt", "yuv420p", "-movflags", "+faststart",
        output_path,
    ])

    # Verify duration
    actual = _get_duration(output_path)
    print(f"Demo video duration: {actual:.2f}s, target: {total_duration:.2f}s")


def split_demo_video(demo_video, segment_durations):
    """Split demo video into 3 clips matching segment durations."""
    total = sum(segment_durations)
    source_duration = _get_duration(demo_video)
    clips = []

    # Calculate split points proportionally by target durations
    split_points = [0]
    cumulative = 0
    for d in segment_durations[:-1]:
        cumulative += d
        split_points.append(cumulative / total * source_duration)
    split_points.append(source_duration)

    for i, (start, end) in enumerate(zip(split_points[:-1], split_points[1:])):
        clip = os.path.join(DEMO_OUTPUT_DIR, f"demo_clip_{i}.mp4")
        audio = os.path.join(AUDIO_DIR, f"slide_{4+i:03d}.mp3")
        extract_video_clip(demo_video, audio, clip, start, end)
        clips.append(clip)

    return clips


def main():
    Path(DEMO_OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

    # Collect audio durations
    audio_files = {i: os.path.join(AUDIO_DIR, f"slide_{i:03d}.mp3") for i in range(11)}
    durations = {i: _get_duration(f) for i, f in audio_files.items()}

    demo_segment_durations = [durations[i] for i in sorted(DEMO_SLIDES)]

    # Record demo video
    demo_video = os.path.join(DEMO_OUTPUT_DIR, "demo_full.mp4")
    asyncio.run(record_demo_video(demo_video, demo_segment_durations))

    # Split into 3 clips
    demo_clips = split_demo_video(demo_video, demo_segment_durations)

    # Build all clips
    clip_paths = []
    for i in range(11):
        audio = audio_files[i]
        output = os.path.join(DEMO_OUTPUT_DIR, f"clip_{i:03d}.mp4")
        if i in DEMO_SLIDES:
            demo_idx = sorted(DEMO_SLIDES).index(i)
            # Already built in split_demo_video
            output = demo_clips[demo_idx]
        else:
            image = os.path.join(PPT_FRAMES_DIR, f"slide_{i:03d}.png")
            build_image_clip(image, audio, output)
        clip_paths.append(output)

    # Concatenate
    concat_file = os.path.join(DEMO_OUTPUT_DIR, "concat.txt")
    with open(concat_file, "w") as f:
        for clip in clip_paths:
            f.write(f"file '{clip}'\n")

    run_ffmpeg([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_file,
        "-c", "copy", FINAL_OUTPUT,
    ])

    print(f"Hybrid video built: {FINAL_OUTPUT}")


if __name__ == "__main__":
    main()
